"""
Austin Model
"""

class Austin(object):
    """Austin Field sets"""
    patient_fields = {
        "patientId": "",
        "patientMrn": "",
        "birthDate": "",
        "dateOfDeath": "",
        "deceasedFlag": "",
        "lastName": "",
        "firstName": "",
        "title": "",
        "middleName": "",
        "countryOfBirth": "",
        "gender": "",
        "indigenousStatus": "",
        "isInterpreterRequired": "",
        "maritalStatus": "",
        "preferredLanguage": "",
        "religion": "",
        "smokingStatus": "",
        "usualPlaceOfResidence": "",
        "postCode": "",
        "startDatetime": "",
        "recordStatus": "",
        "isSuppressed": "",
        "systemUpdateDate": "",
    }
    provider_fields = {
        "providerId": "",
        "providerCode": "",
        "lastName": "",
        "firstName": "",
        "middleName": "",
        "fullName": "",
        "title": "",
        "role": "",
        "recordStatus": "",
        "systemUpdateDate": "",
    }

    allergy_fields = {
        "problemId": "",
        "parentId": "",  # shouldn't be in use
        "mrn": "",
        "patientId": "",
        "episodeId": "",
        "identifier": "",
        "display": "",
        "type": "",
        "notedDate": "",
        "resolvedDate": "",
        "severity": "",
        "status": "",
        "recordStatus": "",
        "startDate": "",
        "systemUpdateDate": "",
        "reactions": "",
    }

    discharge_fields = {
        "documentId": "",
        "episodeId": "",
        "trakCareEpisodeId": "",
        "patientId": "",
        "patientMrn": "",
        "performedDate": "",
        "type": "",
        "documentTitle": "",
        "resultType": "",
        "status": "",
        "performedProviderId": "",
        "performedProviderCode": "",
        "verifiedProviderId": "",
        "verifiedProviderCode": "",
        "containsBlob": "",
        "recordStatus": "",
        "resultBlob": "",
        "systemUpdateDate": "",
    }

    episode_fields = {
        "episodeId": "",
        "patientId": "",
        "patientMrn": "",
        "trakCareEpisodeId": "",
        "type": "",
        "status": "",
        "primaryVisitReason": "",
        "facility": "",
        "location": "",
        "specialty": "",
        "facilityCode": "",
        "locationCode": "",
        "specialtyCode": "",
        "startDate": "",
        "endDate": "",
        "ward": "",
        "careTypeDescription": "",
        "recordStatus": "",
        "systemUpdateDate": "",
    }

    episode_diagnosis_fields = {
        "episodeDiagnosisId": "",
        "episodeId": "",
        "trakCareEpisodeId": "",
        "episodeType": "",
        "patientId": "",
        "patientMrn": "",
        "icdCode": "",
        "icdDescription": "",
        "codeVersion": "",
        "diagnosisRank": "",
        "diagnosisDate": "",
        "type": "",
        "recordStatus": "",
        "systemUpdateDate": "",
        "episodeStartDate": "",
        "episodeEndDate": "",
    }
    medication_order_fields = {
        "medicationAdminId": "",
        "orderId": "",
        "patientId": "",
        "patientMrn": "",
        "episodeId": "",
        "trakCareEpisodeId": "",
        "medicationName": "",
        "medicationAlias": "",
        "medicationDescription": "",
        "volumeDose": "",
        "volumeUnits": "",
        "drugForm": "",
        "frequency": "",
        "prnFlag": "",
        "durationUnits": "",
        "duration": "",
        "indication": "",
        "prnInstructions": "",
        "orderDate": "",
        "display": "",
        "clinicalDisplay": "",
        "orderStatus": "",
        "orderType": "",
        "orderComments": "",
        "orderProviderId": "",
        "orderProviderCode": "",
        "performedProviderCode": "",
        "verifiedProviderCode": "",
        "administrationStatus": "",
        "doseStrength": "",
        "doseUnits": "",
        "doseText": "",
        "administrationRoute": "",
        "administrationSite": "",
        "notGiven": "",
        "notGivenComments": "",
        "startDate": "",
        "endDate": "",
        "recordStatus": "",
        "systemUpdateDate": "",
        "performedProviderId": "",
        "verifiedProviderId": "",
    }

    observation_fields = {
        "observationId": "",
        "episodeId": "",
        "trakCareEpisodeId": "",
        "patientId": "",
        "patientMrn": "",
        "orderId": "",
        "orderDate": "",
        "performedDate": "",
        "resultUpdateDate": "",
        "type": "",
        "observationTitle": "",
        "status": "",
        "result": "",
        "resultUnits": "",
        "performedProviderId": "",
        "performedProviderCode": "",
        "verifiedProviderId": "",
        "verifiedProviderCode": "",
        "startDate": "",
        "eventStartDate": "",
        "eventEndDate": "",
        "recordStatus": "",
        "blob": "",
        "systemUpdateDate": "",
        "endDate": "",
        "containsBlob": "",
    }
    pathology_result_field = {
        "pathResultId": "",
        "episodeId": "",
        "trakCareEpisodeId": "",
        "patientId": "",
        "patientMrn": "",
        "orderId": "",
        "accessionNumber": "",
        "orderDate": "",
        "performedDate": "",
        "resultUpdateDate": "",
        "type": "",
        "typeDescription": "",
        "resultType": "",
        "status": "",
        "result": "",
        "resultUnits": "",
        "normalLow": "",
        "normalHigh": "",
        "containsBlob": "",
        "startDate": "",
        "endDate": "",
        "eventStartDate": "",
        "eventEndDate": "",
        "recordStatus": "",
        "blob": "",
        "systemUpdateDate": "",
    }

    radiology_result_feild = {
        "radiologyResultId": "",
        "episodeId": "",
        "trakCareEpisodeId": "",
        "patientId": "",
        "patientMrn": "",
        "orderId": "",
        "accessionNumber": "",
        "orderDate": "",
        "performedDate": "",
        "resultUpdateDate": "",
        "type": "",
        "typeDescription": "",
        "resultType": "",
        "status": "",
        "result": "",
        "containsBlob": "",
        "startDate": "",
        "endDate": "",
        "eventStartDate": "",
        "eventEndDate": "",
        "recordStatus": "",
        "blob": "",
        "systemUpdateDate": "",
    }
    theater_procedure = {
        "theaterProcedureId": "",
        "episodeId": "",
        "trakCareEpisodeId": "",
        "patientId": "",
        "patientMrn": "",
        "procedureName": "",
        "procedureNotes": "",
        "procedureRank": "",
        "primarySurgeon": "",
        "primarySurgeonId": "",
        "primarySurgeonCode": "",
        "surgicalSpecialty": "",
        "anestheticType": "",
        "procedureStartDate": "",
        "procedureEndDate": "",
        "procedureDuration": "",
        "orderId": "",
        "theaterCaseId": "",
        "recordStatus": "",
        "systemUpdateDate": "",
    }
    theater_procedure_coding = {
        "theaterProcedureCodingId": "",
        "episodeId": "",
        "trakCareEpisodeId": "",
        "episodeType": "",
        "patientId": "",
        "patientMrn": "",
        "codeVersion": "",
        "diagnosisRank": "",
        "procedureCode": "",
        "procedureDescription": "",
        "icdBlock": "",
        "recordStatus": "",
        "systemUpdateDate": "",
    }
