"""
Cedars Model
"""


class Cedars(object):

    ap_report_fields = {
        "patientMrn": "",
        "encId": "",
        "orderId": "",
        "orderStatus": "",
        "procedureCode": "",
        "procedureStatus": "",
        "resultDttm": "",
        "collectionDttm": "",
        "specimenSrcList": "",
        "orderingMD": "",
        "resultMd": "",
        "resultText": "",
    }
    allergy_fields = {
        "patientMrn": "",
        "allergen": "",
        "allergenType": "",
        "allergyType": "",
        "reactions": "",
        "severityLevel": "",
        "reactionComment": "",
        "enteredDate": "",
    }

    encounters_fields = {
        "patientMrn": "",
        "encId": "",
        "admitDate": "",
        "dischargeDate": "",
        "admittingMd": "",
        "attendingMd": "",
        "referringMd": "",
        "pcpMd": "",
        "consultingMd": "",
        "encMajorType": "",
        "encPatientClass": "",
        "encAdmitSource": "",
        "encDischargeDisposition": "",
        "encHospitalService": "",
        "encUnit": "",
        "encStatus1": "",
        "encStatus2": "",
        "encAdmissionType": "",
        "erComplaintText": "",
        "encDx": "",
        "admittingDx": "",
        "admittingDxText": "",
    }
    episode_item_fields = {
        "patientMrn": "",
        "episodeId": "",
        "episodeLine": "",
        "encounterId": "",
        "episodeTypeCode": "",
        "episodeTypeName": "",
        "episodeStatusCode": "",
        "episodeStatusName": "",
        "treatmentPlanId": "",
        "treatmentPlanName": "",
        "treatmentPlanStatus": "",
        "treatmentPlanStartDate": "",
        "treatmentPlanDiscontinueDate": "",
    }

    har_diagnosis_fields = {
        "patientMrn",
        "dischargeDate",
        "icd9Code",
        "icd9Name",
        "providerId",
        "providerName",
        "icd10Codes",
        "encounterIds",
    }

    imaging_report = {
        "patientMrn": "",
        "encId": "",
        "orderId": "",
        "accessionNumber": "",
        "noteEncId": "",
        "noteId": "",
        "orderingMD": "",
        "authMD": "",
        "finalMD": "",
        "dictateMD": "",
        "imgCollectionDttm": "",
        "resultDttm": "",
        "imgProcedure": "",
        "imgABNFlag": "",
        "addendumNoteId": "",
        "addendumDttm": "",
        "imgResultText": "",
        "addendumResultText": "",
    }
    lab_report_line_item = {
        "patientMrn": "",
        "encId": "",
        "labOrderId": "",
        "labLineNumber": "",
        "labOrderInstant": "",
        "loinc": "",
        "labProcedure": "",
        "localTest": "",
        "collectionDttm": "",
        "resultDttm": "",
        "resultNumericValue": "",
        "resultStrValue": "",
        "resultUOM": "",
        "referenceLow": "",
        "referenceHigh": "",
        "dataType": "",
        "shortComment": "",
        "resultStatus": "",
        "labStatus": "",
        "abnormalFlag": "",
        "resultingLab": "",
        "procedureComments": "",
        "testComments": "",
    }

    medication_order = {
        "patientMrn": "",
        "encounterId": "",
        "orderId": "",
        "cedarsMedicationId": "",
        "orderDate": "",
        "priority": "",
        "startDate": "",
        "endDate": "",
        "frequency": "",
        "numDoses": "",
        "thisFieldIsNotPopulated": "",
        "hl7MedicationId": "",
        "medicationName": "",
        "rxnormCode": "",
        "orderStatus": "",
        "medicationStatus": "",
        "dosageMin": "",
        "dosageMax": "",
        "dosageUnits": "",
        "thisFieldIsNotPopulatedEither": "",
        "route": "",
        "site": "",
        "administrationMethod": "",
        "minimumRate": "",
        "maximumRate": "",
        "rateUnits": "",
        "strengthValue": "",
        "strengthUnits": "",
        "orderingProvider": "",
        "authorizingProvider": "",
        "verifyingProvider": "",
        "discontinuationReason": "",
        "authorizationMode": "",
        "patientType": "",
        "instructions": "",
        "prnReasons": "",
    }
    medication_order_component = {
        "patientMrn": "",
        "encounterId": "",
        "orderId": "",
        "sequenceNumber": "",
        "internalMedicationId": "",
        "type": "",
        "hl7ComponentId": "",
        "displayName": "",
        "amount": "",
        "amountUnits": "",
        "strengthValue": "",
        "strengthUnits": "",
        "rxnormCode": "",
        "orderDate": "",
        "startDate": "",
        "endDate": "",
    }
    patient_fields = {
        "patientMrn": "",
        "lastName": "",
        "firstName": "",
        "middleName": "",
        "birthDate": "",
        "age": "",
        "ethnicity": "",
        "sex": "",
        "races": "",
        "zip": "",
        "dateOfDeath": "",
        "mortalityStatus": "",
        "researchOptOut": "",
        "confidential": "",
        "email": "",
        "phoneNumberWork": "",
        "phoneNumberCell": "",
        "phoneNumberHome": "",
    }

    note_fields = {
        "patientMrn": "",
        "noteId": "",
        "noteLineNo": "",
        "encId": "",
        "encMajorType": "",
        "noteDos": "",
        "noteLastFiledDttm": "",
        "noteType": "",
        "noteCreateProv": "",
        "noteCreateDttm": "",
        "noteSignProv": "",
        "noteFirstSignDttm": "",
        "noteCurrAuth": "",
        "encType": "",
        "visitType": "",
        "noteText": "",
    }
    problem_fields = {
        "patientMrn": "",
        "problemID": "",
        "problemDX": "",
        "problemDescription": "",
        "problemICD9List": "",
        "problemICD10List": "",
        "problemNotedDttm": "",
        "problemResolvedDttm": "",
        "problemEntryDttm": "",
        "problemUpdateDttm": "",
        "problemExternalDxId": "",
        "problemEncId": "",
        "problemStatus": "",
        "problemClass": "",
        "problemPriority": "",
        "problemComment": "",
    }
    provider_fields = {
        "cedarsId": "",
        "lastName": "",
        "firstName": "",
        "specialty": "",
        "phone": "",
        "providerType": "",
        "providerRecord": "",
        "addressLine1": "",
        "addressLine2": "",
        "addressLine3": "",
        "city": "",
        "state": "",
        "zip": "",
    }

    social_history_field = {
        "patientMrn": "",
        "encId": "",
        "contactDttm": "",
        "admitDttm": "",
        "dischargeDttm": "",
        "weight": "",
        "height": "",
        "smokingHistory": "",
        "smokingUsage": "",
        "smokingQuitDttm": "",
        "smokingStartDttm": "",
        "smokingComment": "",
        "smokingPacksPerDay": "",
        "smokingYears": "",
        "smokelessTobaccoUse": "",
        "alcoholHistory": "",
        "alcoholOzPerWeek": "",
        "alcoholComment": "",
    }
