"""
Jefferson Model
"""


class Jefferson(object):
    """Jefferson Fields"""

    admission_note_fields = {
        "insuranceMemberId": "",
        "patientMrn": "",
        "patientFirstName": "",
        "patientLastName": "",
        "birthDate": "",
        "encounterId": "",
        "admissionDate": "",
        "attendingProviderNpi": "",
        "admissionNoteText": "",
        "seqNum": "",
        "noteId": "",
    }

    allergy_fields = {
        "insuranceMemberId": "",
        "patientMrn": "",
        "patientFirstName": "",
        "patientLastName": "",
        "birthDate": "",
        "encounterId": "",
        "admissionDate": "",
        "attendingProviderNpi": "",
        "allergyId": "",
        "noKnownAllergies": "",
        "allergenName": "",
        "allergenType": "",
        "allergyReactionDescription": "",
        "allergyReactionType": "",
        "allergyRecordDate": "",
        "allergyStatus": "",
        "comments": "",
        "allergyLastReviewedDate": "",
    }

    imaging_report_fields = {
        "insuranceMemberId": "",
        "patientMrn": "",
        "patientFirstName": "",
        "patientLastName": "",
        "birthDate": "",
        "encounterId": "",
        "admissionDate": "",
        "attendingProviderNpi": "",
        "orderName": "",
        "procName": "",
        "procOrderId": "",
        "resultNoteCSN": "",
        "noteTextSeqNum": "",
        "noteText": "",
    }

    patient_fields = {
        "patientId": "",
        "patientMrn": "",
        "firstName": "",
        "middleName": "",
        "lastName": "",
        "suffixName": "",
        "birthDate": "",
        "city": "",
        "state": "",
        "zip": "",
        "deceasedDate": "",
        "genderCode": "",
        "genderDescription": "",
        "maritalStatusCode": "",
        "maritalStatusDescription": "",
        "raceCode": "",
        "raceDescription": "",
        "ethnicityCode": "",
        "ethnicityDescription": "",
        "primaryCareProviderFullName": "",
        "primaryCareProviderNPI": "",
        "isAdvanceDirectiveChecked": "",
    }
    out_patient_field = {
        "patientId": "",
        "patientMrn": "",
        "firstName": "",
        "middleName": "",
        "lastName": "",
        "suffixName": "",
        "birthDate": "",
        "city": "",
        "state": "",
        "zip": "",
        "deceasedDate": "",
        "genderCode": "",
        "genderDescription": "",
        "maritalStatusCode": "",
        "maritalStatusDescription": "",
        "raceCode": "",
        "raceDescription": "",
        "ethnicityCode": "",
        "ethnicityDescription": "",
        "primaryCareProviderFullName": "",
        "primaryCareProviderNPI": "",
    }

    problem_list_fields = {
        "insuranceMemberId": "",
        "patientMrn": "",
        "patientFirstName": "",
        "patientLastName": "",
        "birthDate": "",
        "encounterId": "",
        "admissionDate": "",
        "attendingProviderNpi": "",
        "problemListId": "",
        "dxCode": "",
        "dxDescription": "",
        "dxCodeStandard": "",
        "problemPresentOnAdmission": "",
        "problemOnsetDate": "",
        "problemResolvedDate": "",
        "problemListComment": "",
        "problemListLastReviewedDate": "",
        "chronicProblemFlag": "",
    }
    provider_fields = {
        "firstName": "",
        "middleName": "",
        "lastName": "",
        "suffixName": "",
        "credentials": "",
        "npi": "",
        "id": "",
        "specialtyCode": "",
        "specialtyDescription": "",
        "mainAddress1": "",
        "mainAddress2": "",
        "mainCity": "",
        "mainState": "",
        "mainZip": "",
        "mainPhone": "",
    }
    immunization_fields = {
        "insuranceMemberId": "",
        "patientMrn": "",
        "patientFirstName": "",
        "patientLastName": "",
        "birthDate": "",
        "primaryKey": "",
        "cptCode": "",
        "description": "",
        "cvxCode": "",
        "administrationDate": "",
        "refusalReasonCode": "",
        "refusalReasonDescription": "",
        "comments": "",
    }

    lab_result_fields = {
        "insuranceMemberId": "",
        "patientMrn": "",
        "patientFirstName": "",
        "patientLastName": "",
        "birthDate": "",
        "encounterId": "",
        "encounterDate": "",
        "authorizingProviderNpi": "",
        "encounterProviderNpi": "",
        "orderName": "",
        "orderId": "",
        "labResultId": "",
        "loincId": "",
        "loincDescription": "",
        "collectionDate": "",
        "resultStatus": "",
        "resultDate": "",
        "resultType": "",
        "resultComponentName": "",
        "resultValue": "",
        "unitOfMeasure": "",
        "resultDescription": "",
        "abnormal": "",
        "refNormVals": "",
        "gender": "",
    }

    consult_note_fields = {
        "insuranceMemberId": "",
        "patientMrn": "",
        "patientFirstName": "",
        "patientLastName": "",
        "birthDate": "",
        "encounterId": "",
        "admissionDate": "",
        "attendingProviderNpi": "",
        "consultationDate": "",
        "consultationNoteText": "",
        "consultNoteSequenceNumber": "",
        "noteId": "",
    }

    discharge_information_fields = {
        "insuranceMemberId": "",
        "patientMrn": "",
        "patientFirstName": "",
        "patientLastName": "",
        "birthDate": "",
        "encounterId": "",
        "admissionDate": "",
        "attendingProviderNpi": "",
        "orderName": "",
        "orderId": "",
        "orderCode": "",
        "orderCodeStandard": "",
        "orderingDate": "",
        "orderType": "",
        "orderingComment": "",
        "assocDxId": "",
        "assocDxDesc": "",
    }

    discharge_notes_fields = {
        "insuranceMemberId": "",
        "patientMrn": "",
        "patientFirstName": "",
        "patientLastName": "",
        "birthDate": "",
        "encounterId": "",
        "admissionDate": "",
        "attendingProviderNpi": "",
        "dischargeNoteText": "",
        "dischargeNoteSeqNum": "",
        "noteId": "",
    }

    encounter_diagnosis_fields = {
        "insuranceMemberId": "",
        "patientMrn": "",
        "patientFirstName": "",
        "patientLastName": "",
        "birthDate": "",
        "encounterId": "",
        "encounterDate": "",
        "patEncCsnId": "",
        "line": "",
        "authorizingProviderNpi": "",
        "encounterProviderNpi": "",
        "dxCode": "",
        "dxDescription": "",
        "dxCodeStandard": "",
        "dxChronic": "",
        "primaryIndicator": "",
    }

    procedure_result_fields = {
        "insuranceMemberId": "",
        "patientMrn": "",
        "patientFirstName": "",
        "patientLastName": "",
        "birthDate": "",
        "encounterId": "",
        "admissionDate": "",
        "attendingProviderNpi": "",
        "orderName": "",
        "procName": "",
        "procOrderId": "",
        "procDate": "",
        "procedureCode": "",
        "procedureCodeStandard": "",
        "resultDate": "",
        "procedureType": "",
        "procedureResultStatus": "",
        "resultValue": "",
        "resultDescription": "",
        "abnormal": "",
        "comments": "",
    }

    social_history_fields = {
        "insuranceMemberId": "",
        "patientMrn": "",
        "patientFirstName": "",
        "patientLastName": "",
        "birthDate": "",
        "encounterId": "",
        "admissionDate": "",
        "attendingProviderNpi": "",
        "socialHistoryId": "",
        "socialHistoryDiscussedDate": "",
        "socialHxType": "",
        "socialHxUse": "",
        "alcoholUseCode": "",
        "alcoholPerWeek": "",
        "alcoholComment": "",
        "smokingStatus": "",
        "smokingItemsUsed": "",
        "smokingItemUseYears": "",
        "smokingItemQuitDate": "",
        "smokingComment": "",
        "lastReviewedDate": "",
    }

    medication_record_fields = {
        "insuranceMemberId": "",
        "patientMrn": "",
        "patientFirstName": "",
        "patientLastName": "",
        "birthDate": "",
        "encounterId": "",
        "encounterDate": "",
        "authorizingProviderNpi": "",
        "encounterProviderNpi": "",
        "medicationName": "",
        "orderId": "",
        "orderDate": "",
        "ndc": "",
        "rxDraw": "",
        "dosage": "",
        "route": "",
        "frequency": "",
        "quantity": "",
        "refills": "",
        "prnComment": "",
        "duration": "",
        "prescriptionInstructions": "",
        "defaultPharmacy": "",
        "pharmacyAddress": "",
        "pharmacyId": "",
        "authProvId": "",
        "rxNormCode": "",
        "orderStatusCode": "",
        "orderStatusDesc": "",
        "orderClass": "",
    }
    medication_administration_record = {
        "insuranceMemberId": "",
        "patientMrn": "",
        "patientFirstName": "",
        "patientLastName": "",
        "birthDate": "",
        "encounterId": "",
        "admissionDate": "",
        "attendingProviderNpi": "",
        "medicationName": "",
        "medicationOrderId": "",
        "line": "",
        "ndc": "",
        "administrationDate": "",
        "administrationTime": "",
        "dose": "",
        "route": "",
        "comment": "",
        "reason": "",
        "isPatientSupplied": "",
    }

    progress_tracker_note_fields = {
        "insuranceMemberId",
        "patientMrn",
        "patientFirstName",
        "patientLastName",
        "birthDate",
        "encounterId",
        "encounterDate",
        "authorizingProviderNpi",
        "encounterProviderNpi",
        "noteId",
        "noteTextSeqNum",
        "noteText",
    }
