"""
MDAnderson Model
"""


class MdAndersion(object):

    allergy_fields = {
        "siteId": "",
        "PT_MRN": "",
        "allergen": "",
        "allergenType": "",
        "allergyType": "",
        "reactions": "",
        "severityLevel": "",
        "reactionComment": "",
        "enteredDate": "",
    }
    encounter_fields = {
        "siteId": "",
        "PT_MRN": "",
        "encId": "",
        "encAdmitDttm": "",
        "encDischargeDttm": "",
        "admitProvider": "",
        "attendProvider": "",
        "referProvider": "",
        "pcpProvider": "",
        "consultProvider": "",
        "encMajorType": "",
        "encPatientClass": "",
        "admitSrc": "",
        "encStatus1": "",
        "encStatus2": "",
        "admissionType": "",
        "chiefComplaint": "",
        "dxCode": "",
        "admitDx": "",
        "admitDxText": "",
    }

    genomic_report_fields = {
        "siteId": "",
        "PT_MRN": "",
        "reportDttm": "",
        "reportId": "",
        "reportText": "",
        "geneCodes": "",
    }
    imaging_report_fields = {
        "siteId": "",
        "PT_MRN": "",
        "orderId": "",
        "orderProvider": "",
        "authProvider": "",
        "finalProvider": "",
        "dictateProvider": "",
        "collectionDttm": "",
        "resultDttm": "",
        "addendNoteId": "",
        "addendDttm": "",
        "imgResultText": "",
        "addendResultText": "",
        "encId": "",
    }
    lab_report_fields = {
        "siteId": "",
        "PT_MRN": "",
        "labOrderId": "",
        "labLineNo": "",
        "labLoinc": "",
        "labProcedure": "",
        "labRsltCollectionDttm": "",
        "labRsltDttm": "",
        "labRsltValue": "",
        "labRsltUom": "",
        "labDataType": "",
        "resultingLab": "",
        "labProcComments": "",
        "labTestComment": "",
        "encId": "",
    }
    mar_fields = {
        "siteId": "",
        "PT_MRN": "",
        "ordId": "",
        "ordMedDttm": "",
        "ordMedStartDttm": "",
        "ordMedEndDttm": "",
        "ordMedFrequency": "",
        "ordMedNoOfDoses": "",
        "ordMedNm": "",
        "ordMedRxNorm": "",
        "ordMedAmtMin": "",
        "ordMedAmtMax": "",
        "ordMedUnits": "",
        "orderingProvider": "",
        "authorizingProvider": "",
        "verifyingProvider": "",
        "instructions": "",
        "prnReasons": "",
        "encId": "",
    }
    note_field = {
        "siteId": "",
        "PT_MRN": "",
        "noteId": "",
        "encounterType": "",
        "noteDos": "",
        "noteType": "",
        "noteCreateProvider": "",
        "noteSignProvider": "",
        "noteFirstSignDttm": "",
        "noteCurrentAuth": "",  # "contactDateReal":"", "line":"", "sort":"",
        "noteText": "",
        "encId": "",
    }
    pathology_report_fields = {
        "siteId": "",
        "PT_MRN": "",
        "apOrderId": "",
        "apOrderStsCd": "",
        "resultDttm": "",
        "collectionDttm": "",
        "specimenSrcList": "",
        "orderMd": "",
        "resultMd": "",
        "resultText": "",
        "encId": "",
    }

    patient_fields = {
        "siteId": "",
        "PT_MRN": "",
        "lastName": "",
        "firstName": "",
        "middleName": "",
        "dob": "",
        "ethnicity": "",
        "sex": "",
        "race": "",
        "zip": "",
        "deathDttm": "",
        "status": "",
        "weight": "",
        "height": "",
    }
