#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""This Module Stores Field Mapping"""


class UhHospital(object):
    """Field Maps for UH Hospital"""

    patient_fields = {
        "SITE_ID": "",
        "PT_MRN": "",
        "PT_LAST_NAME": "",
        "PT_FIRST_NAME": "",
        "PT_MIDDLE_NAME": "",
        "PT_BIRTH_DTTM": "",
        "PT_ETHNICITY": "",
        "PT_SEX": "",
        "PT_RACE": "",
        "PT_ZIP": "",
        "PT_DEATH_DTTM": "",
        "PT_STATUS": "",
        "PT_WEIGHT": "",
        "PT_HEIGHT": "",
    }

    allergy_fields = {
        "SITE_ID": "",
        "PT_MRN": "",
        "ALLERGY_ALRGN": "",
        "ALLERGY_ALRGN_TYPE": "",
        "ALLERGY_TYPE": "",
        "ALLERGY_RXN": "",
        "ALLERGY_SVRTY_LEVEL": "",
        "ALLERGY_RXN_COMMENT": "",
        "ALLERGY_ENTERED_DTTM": "",
        "ALLERGY_ID": "",
        "ALLERGY_CATEGORY": "",
        "ALLERGY_STATUS": "",
    }

    ambulatory_imaging_report_feilds = {
        "SITE_ID": "",
        "PT_MRN": "",
        "ORD_ID": "",
        "ORD_MD": "",
        "AUTH_MD," "FINAL_MD": "",
        "DICTATE_MD": "",
        "IMG_COLLECTION_DTTM": "",
        "IMG_RESLT_DTTM": "",
        "ADDEND_NOTE_ID": "",
        "ADDEND_DTTM": "",
        "IMG_RSLT_TEXT": "",
        "ADDEND_RSLT_TEXT": "",
        "ENC_ID": "",
    }

    ambulatory_medication_report_fields = {
        "SITE_ID": "",
        "PT_MRN": "",
        "ORD_ID": "",
        "ORD_MD": "",
        "AUTH_MD," "FINAL_MD": "",
        "DICTATE_MD": "",
        "IMG_COLLECTION_DTTM": "",
        "IMG_RESLT_DTTM": "",
        "ADDEND_NOTE_ID": "",
        "ADDEND_DTTM": "",
        "IMG_RSLT_TEXT": "",
        "ADDEND_RSLT_TEXT": "",
        "ENC_ID": "",
    }

    ap_report_fields = {
        "SITE_ID": "",
        "PT_MRN": "",
        "AP_ORDER_ID": "",
        "AP_ORDER_STS_CD": "",
        "RESULT_DTTM": "",
        "COLLECTION_DTTM": "",
        "SPECIMEN_SRC_LIST": "",
        "ORD_MD": "",
        "RESULT_MD": "",
        "RESULT_TEXT": "",
        "ENC_ID": "",
    }

    encounters_fields = {
        "SITE_ID": "",
        "PT_MRN": "",
        "ENC_ID": "",
        "ENC_ADMIT_DTTM": "",
        "ENC_DISCHARGE_DTTM": "",
        "ADMIT_MD": "",
        "ATND_MD": "",
        "REFER_MD": "",
        "PCP_MD": "",
        "CONSULT_MD": "",
        "ENC_MAJOR_TYPE": "",
        "ENC_PATIENT_CLASS": "",
        "ENC_ADMIT_SOURCE": "",
        "ENC_STATUS_1": "",
        "ENC_STATUS_2": "",
        "ENC_ADMISSION_TYPE": "",
        "ER_COMPLAINT": "",
        "ENC_DX": "",
        "ADMIT_DX": "",
        "ADMIT_DX_TEXT": "",
    }

    imaging_report_fields = {
        "SITE_ID": "",
        "PT_MRN": "",
        "ORD_ID": "",
        "ORD_MD": "",
        "AUTH_MD": "",
        "FINAL_MD": "",
        "DICTATE_MD": "",
        "IMG_COLLECTION_DTTM": "",
        "IMG_RESLT_DTTM": "",
        "ADDEND_NOTE_ID": "",
        "ADDEND_DTTM": "",
        "IMG_RESLT_TEXT": "",
        "ADDEND_RESLT_TEXT": "",
        "ENC_ID": "",
    }

    lab_report_fields = {
        "SITE_ID": "",
        "PT_MRN": "",
        "LAB_ORDER_ID": "",
        "LAB_LINE_NO": "",
        "LAB_LOINC": "",
        "LAB_PROCEDURE": "",
        "LAB_RSLT_COLLECTION_DTTM": "",
        "LAB_RSLT_DTTM": "",
        "LAB_RSLT_VALUE": "",
        "LAB_RSLT_UOM": "",
        "LAB_DATA_TYPE": "",
        "RESULTING_LAB": "",
        "LAB_PROC_COMMENTS": "",
        "LAB_TEST_COMMENT": "",
        "ENC_ID": "",
    }

    medication_fields = {
        "SITE_ID": "",
        "PT_MRN": "",
        "ORD_ID": "",
        "ORD_MED_START_DTTM": "",
        "ORD_MED_END_DTTM": "",
        "ORD_MED_FREQUENCY": "",
        "ORD_MED_NO_OF_DOSES": "",
        "ORD_MED_NM": "",
        "ORD_MED_RXNORM": "",
        "ORD_MED_AMT_MIN": "",
        "ORD_MED_AMT_MAX": "",
        "ORD_MED_UNITS": "",
        "ORD_MED_ORDERING_PROV": "",
        "ORD_MED_VERIFYING_PROV": "",
        "ORD_MED_ADMIN_INSTRUCTIONS": "",
        "ORD_MED_PRN_REASONS": "",
        "ENC_ID": "",
    }

    notes_fields = {
        "SITE_ID": "",
        "PT_MRN": "",
        "NOTE_ID": "",
        "ENC_MAJOR_TYPE": "",
        "NOTE_DOS": "",
        "NOTE_TYPE": "",
        "NOTE_CREATE_PROV": "",
        "NOTE_SIGN_PROV": "",
        "NOTE_FIRST_SIGN_DTTM": "",
        "NOTE_CURRENT_AUTH": "",
        "NOTE_TEXT": "",
        "ENC_ID": "",
    }
    problem_fields = {
        "SITE_ID": "",
        "PT_MRN": "",
        "PROB_ID": "",
        "PROB_DIAGNOSIS": "",
        "PROB_DESC": "",
        "PROB_ICD_LIST": "",
        "PROB_NOTED_DTTM": "",
        "PROB_RESOLVED_DTM": "",
        "PROB_STATUS": "",
        "PROB_COMMENT": "",
        "ENC_ID": "",
    }

    provider_fields = {
        "SITE_ID": "",
        "IDENTITY_ID": "",
        "PROV_LAST_NAME": "",
        "PROV_FIRST_NAME": "",
        "SPECIALTY": "",
        "PHONE": "",
        "EMAIL": "",
        "PROVIDER_TYPE": "",
        "ADDR_LINE_1": "",
        "ADDR_LINE_2": "",
        "ADDR_LINE_3": "",
        "CITY": "",
        "STATE": "",
        "ZIP": "",
    }
    site_fields = {
        "SITE_ID": "",
        "SITE_NAME": "",
        "PHONE": "",
        "EMAIL": "",
        "ADDR_LINE_1": "",
        "ADDR_LINE_2": "",
        "ADDR_LINE_3": "",
        "CITY": "",
        "STATE": "",
        "ZIP": "",
        "URL": "",
    }


class Mimic(object):
    """Mimic Fields"""

    cpt_fields = {
        "rowId": "",
        "subjectId": "",
        "hadmId": "",
        "costCenter": "",
        "chartDate": "",
        "cptCode": "",
        "cptNumber": "",
        "cptSuffix": "",
        "ticketIdSeq": "",
        "sectionHeader": "",
        "subsectionHeader": "",
        "description": "",
    }
    admission_fields = {
        "rowId": "",
        "subjectId": "",
        "hadmId": "",
        "admitTime": "",
        "dischTime": "",
        "deathTime": "",
        "admissionType": "",
        "admmissionLocation": "",
        "dischargeLocation": "",
        "insurance": "",
        "language": "",
        "religion": "",
        "matialStatus": "",
        "ethnicity": "",
        "edRegTime": "",
        "edOutTime": "",
        "diagnosis": "",
        "hospitalExpireFlag": "",
        "hasCharEventData": "",
    }
    d_lab_item_fields = {
        "rowId": "",
        "itemId": "",
        "label": "",
        "fluid": "",
        "category": "",
        "loincCode": "",
    }

    icd9_fields = {"rowId": "", "icd9Code": "", "shortTitle": "", "longTitle": ""}

    iccd_diagnosis_fields = {
        "rowId": "",
        "subjectId": "",
        "hadmId": "",
        "seqNum": "",
        "icd9Code": "",
    }
    icu_stay_fields = {
        "rowId": "",
        "subjectId": "",
        "hadmId": "",
        "icuStayId": "",
        "dbSource": "",
        "firstCareUnit": "",
        "lastCareUnit": "",
        "firstWardId": "",
        "lastWardId": "",
        "inTime": "",
        "outTime": "",
        "los": "",
    }
    physician_notes_fields = {
        "rowId": "",
        "subjectId": "",
        "hadmId": "",
        "chartDate": "",
        "chartTime": "",
        "storeTime": "",
        "category": "",
        "description": "",
        "cgId": "",
        "isError": "",
        "text": "",
    }

    lab_report_fields = {
        "rowId": "",
        "subjectId": "",
        "hadmId": "",
        "itemId": "",
        "chartTime": "",
        "value": "",
        "valueNum": "",
        "valueUOM": "",
        "flag": "",
    }

    prescription_fields = {
        "rowId": "",
        "subjectId": "",
        "hadmId": "",
        "icuStayId": "",
        "startDate": "",
        "endDate": "",
        "drugType": "",
        "drug": "",
        "drugNamePOE": "",
        "drugNameGeneric": "",
        "forumularyDrugCode": "",
        "gsn": "",
        "ndc": "",
        "prodStrength": "",
        "doseValRx": "",
        "doseUnitRx": "",
        "formValDisp": "",
        "formUnitDisp": "",
        "route": "",
    }

    provider_fields = {
        "providerId": "",
        "lastName": "",
        "middleName": "",
        "firstName": "",
        "providerType": "",
        "specialty": "",
    }

    class Athena(object):

        allergy_fields = {
            "stub_1": "",
            "stub_2": "",
            "stub_3": "",
            "stub_4": "",
            "stub_5": "",
            "stub_6": "",
            "stub_7": "",
            "stub_8": "",
            "stub_9": "",
            "stub_10": "",
            "stub_11": "",
            "stub_12": "",
            "stub_13": "",
            "stub_14": "",
            "stub_15": "",
            "stub_16": "",
            "stub_17": "",
            "stub_18": "",
            "stub_19": "",
            "stub_20": "",
            "stub_21": "",
            "stub_22": "",
            "siteId": "",
            "patientMrn": "",
            "allergen": "",
            "allergenType": "",
            "allergyType": "",
            "reactions": "",
            "severityLevel": "",
            "reactionComment": "",
            "enteredDate": "",
            "allergyId": "",
            "allergyCategory": "",
            "status": "",
        }

        encounter_fields = {
            "siteId": "",
            "stub_2": "",
            "stub_3": "",
            "encId": "",
            "ptMrn": "",
            "stub_6": "",
            "stub_7": "",
            "stub_8": "",
            "stub_9": "",
            "stub_10": "",
            "encMajorType": "",
            "admitProvider": "",
            "attendProvider": "",
            "encAdmitDttm": "",
            "encStatus1": "",
            "stub_16": "",
            "stub_17": "",
            "stub_18": "",
            "encDischargeDttm": "",
            "stub_20": "",
            "stub_21": "",
            "stub_22": "",
            "encStatus2": "",
            "stub_24": "",
            "encPatientClass": "",
            "stub_26": "",
        }

        lab_fields = {
            "stub_1": "",
            "stub_2": "",
            "stub_3": "",
            "stub_4": "",
            "stub_5": "",
            "stub_6": "",
            "stub_7": "",
            "stub_8": "",
            "stub_9": "",
            "stub_10": "",
            "siteId": "",
            "ptMrn": "",
            "labOrderId": "",
            "labLineNo": "",
            "labLoinc": "",
            "labProcedure": "",
            "labRsltCollectionDttm": "",
            "labRsltDttm": "",
            "labRsltValue": "",
            "labRsltUom": "",
            "labDataType": "",
            "resultingLab": "",
            "labProcComments": "",
            "labTestComment": "",
            "encId": "",
        }
        mr_fields = {
            "stub_1": "",
            "stub_2": "",
            "stub_3": "",
            "stub_4": "",
            "stub_5": "",
            "stub_6": "",
            "stub_7": "",
            "stub_8": "",
            "stub_9": "",
            "stub_10": "",
            "stub_11": "",
            "stub_12": "",
            "stub_13": "",
            "stub_14": "",
            "stub_15": "",
            "stub_16": "",
            "stub_17": "",
            "stub_18": "",
            "siteID": "",
            "ptMrn": "",
            "ordId": "",
            "ordMedStartDttm": "",
            "ordMedEndDttm": "",
            "ordMedFrequency": "",
            "ordMedNoOfDoses": "",
            "ordMedNm": "",
            "ordMedRxNorm": "",
            "ordMedAmtMin": "",
            "ordMedAmtMax": "",
            "ordMedUnits": "",
            "ordMedOrderingProv": "",
            "ordMedVerifyingProv": "",
            "ordMedAdminInstructions": "",
            "ordMedPrnReasons": "",
            "encId": "",
        }
        patient_fields = {
            "siteId": "",
            "stub_2": "",
            "stub_3": "",
            "ptMrn": "",
            "stub_5": "",
            "firstName": "",
            "lastName": "",
            "middleName": "",
            "stub_9": "",
            "sex": "",
            "dob": "",
            "stub_12": "",
            "stub_13": "",
            "stub_14": "",
            "stub_15": "",
            "zip": "",
            "stub_17": "",
            "stub_18": "",
            "stub_19": "",
            "stub_20": "",
            "stub_21": "",
            "stub_22": "",
            "stub_23": "",
            "ethnicity": "",
            "stub_25": "",
            "race": "",
            "stub_27": "",
            "stub_28": "",
            "stub_29": "",
            "stub_30": "",
            "deathDttm": "",
            "status": "",
            "stub_33": "",
            "stub_34": "",
            "stub_35": "",
            "stub_36": "",
            "stub_37": "",
            "stub_38": "",
            "stub_39": "",
            "stub_40": "",
            "stub_41": "",
            "stub_42": "",
            "stub_43": "",
            "stub_44": "",
            "stub_45": "",
            "stub_46": "",
            "stub_47": "",
            "stub_48": "",
            "stub_49": "",
            "stub_50": "",
            "stub_51": "",
            "stub_52": "",
            "stub_53": "",
            "stub_54": "",
            "stub_55": "",
            "stub_56": "",
            "stub_57": "",
            "stub_58": "",
            "stub_59": "",
            "stub_60": "",
            "stub_61": "",
            "stub_62": "",
            "stub_63": "",
            "stub_64": "",
            "stub_65": "",
            "stub_66": "",
            "stub_67": "",
            "stub_68": "",
            "stub_69": "",
            "stub_70": "",
            "stub_71": "",
            "stub_72": "",
            "stub_73": "",
            "stub_74": "",
            "stub_75": "",
            "stub_76": "",
            "stub_77": "",
            "stub_78": "",
            "stub_79": "",
            "stub_80": "",
            "stub_81": "",
            "stub_82": "",
            "stub_83": "",
            "stub_84": "",
            "stub_85": "",
            "stub_86": "",
            "stub_87": "",
            "stub_88": "",
            "stub_89": "",
            "stub_90": "",
            "stub_91": "",
            "stub_92": "",
            "stub_93": "",
            "stub_94": "",
            "stub_95": "",
            "stub_96": "",
            "stub_97": "",
            "stub_98": "",
            "stub_99": "",
        }

        provider_fields = {
            "siteId": "",
            "identityId": "",
            "lastName": "",
            "firstName": "",
            "specialty": "",
            "phone": "",
            "email": "",
            "providerType": "",
            "addressLine1": "",
            "addressLine2": "",
            "addressLine3": "",
            "city": "",
            "state": "",
            "zip": "",
        }

        social_history_fields = {
            "stub_1": "",
            "stub_2": "",
            "stub_3": "",
            "stub_4": "",
            "stub_5": "",
            "stub_6": "",
            "stub_7": "",
            "stub_8": "",
            "stub_9": "",
            "stub_10": "",
            "stub_11": "",
            "stub_12": "",
            "stub_13": "",
            "stub_14": "",
            "ptMrn": "",
            "encId": "",
            "hxContactDttm": "",
            "smokingQuitDttm": "",
            "smokingStartDttm": "",
            "smokePpd": "",
            "smokeYrs": "",
            "smokeTobUse": "",
            "smokelessTobUse": "",
            "smokeComment": "",
        }
